/*
 * This file is generated by jOOQ.
 */
package xyz.zhouzhaodong.jooq.dao;


import xyz.zhouzhaodong.jooq.dao.tables.Jooq;


/**
 * Convenience access to all tables in jooq
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.jooq</code>.
     */
    public static final Jooq JOOQ_ = Jooq.JOOQ_;
}
