/*
 * This file is generated by jOOQ.
 */
package xyz.zhouzhaodong.jooq.dao.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import xyz.zhouzhaodong.jooq.dao.tables.Jooq;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqRecord extends UpdatableRecordImpl<JooqRecord> implements Record4<String, Integer, String, Integer> {

    private static final long serialVersionUID = -879021896;

    /**
     * Setter for <code>jooq.jooq.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq.jooq.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jooq.jooq.age</code>.
     */
    public void setAge(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq.jooq.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jooq.jooq.address</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq.jooq.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq.jooq.id</code>.
     */
    public void setId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>jooq.jooq.id</code>.
     */
    public Integer getId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Jooq.JOOQ_.NAME;
    }

    @Override
    public Field<Integer> field2() {
        return Jooq.JOOQ_.AGE;
    }

    @Override
    public Field<String> field3() {
        return Jooq.JOOQ_.ADDRESS;
    }

    @Override
    public Field<Integer> field4() {
        return Jooq.JOOQ_.ID;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public Integer component2() {
        return getAge();
    }

    @Override
    public String component3() {
        return getAddress();
    }

    @Override
    public Integer component4() {
        return getId();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public Integer value2() {
        return getAge();
    }

    @Override
    public String value3() {
        return getAddress();
    }

    @Override
    public Integer value4() {
        return getId();
    }

    @Override
    public JooqRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public JooqRecord value2(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public JooqRecord value3(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public JooqRecord value4(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public JooqRecord values(String value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqRecord
     */
    public JooqRecord() {
        super(Jooq.JOOQ_);
    }

    /**
     * Create a detached, initialised JooqRecord
     */
    public JooqRecord(String name, Integer age, String address, Integer id) {
        super(Jooq.JOOQ_);

        set(0, name);
        set(1, age);
        set(2, address);
        set(3, id);
    }
}
